version: '3.4'

services:
  tiendaservicios.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6104:80"
      - "6105:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  tiendaservicios.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6106:80"

  tiendaservicios.api.carritocompra:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services_Liros=http://localhost:6106
    ports:
      - "6107:80"
